### ISSUE TITLE
Improve Documentations (Sprint #1)

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/ant-media-documentation#15]
- [x] ant-media/Ant-Media-Server#4651 Update JS SDK with the latest functions and callbacks
- [x] ant-media/Ant-Media-Server#4676 Automate JavaScript SDK Reference Doc
- [x] ant-media/Ant-Media-Server#4652 Add parameter type and return type to JS SDK
- [ ] ant-media/ant-media-documentation#10 Automate Android SDK Reference Doc
- [ ] ant-media/Ant-Media-Server#4658 Automate iOS SDK Reference Doc
- [ ] ant-media/Ant-Media-Server#4656 Automate Flutter SDK Reference Doc
- [ ] ant-media/Ant-Media-Server#4655 Automate React Native SDK Reference Doc
- [ ] ant-media/ant-media-documentation#11 Add video tutorials to each documentation page
- [ ] ant-media/Ant-Media-Server#4760 Improve the explanation of the Time based One Time Password (TOTP) creation process.
- [x] ant-media/Ant-Media-Server#4757 Enable searching of the documentation from within the AMS dashboard 
- [ ] ant-media/Ant-Media-Server#4553 Sample documentation for localVideoElement and remoteVideoElement
- [ ] Virtual Background Support
- [ ] Zixi Integration with AMS (There is a blogpost)
- [ ] Free Domain and SSL support - Update setting up SSL document
- [x] TURN Server (Current document needs refactoring about TURN configuration on the server side and client side)
- [x] HLS Load Test
- [ ] Setting up Kubernetes cluster for Google Cloud and making load tests for WebRTC and HLS playback
- [ ] Mention Prometheus Expoter in monitoring the servers documentation ant-media/Ant-Media-Server#3122

**Comment by asharamseervi** [comment]
Kindly keep updating your progress here. So, everyone knows, where we had reached so far.

**Comment by timantmedia** [comment]
Compare other SDK documentation sites to figure out what we want it to look like.

**Comment by mustafaboleken** [comment]
We just change the way we work on documentation, I think it’s time to close this one.
